### PR TITLE
Java 8!

### PR DESCRIPTION
**Pull request by kaidamasaki**

### CODE REVIEW

**Comment by kaidamasaki** [comment]
Successful dockerize build: http://jenkins.aws-us-west-2-infrastructure.socrata.net/job/dockerize/390/

**Comment by znep** [comment]
So this looks good as far as it goes, do we have a plan for building or at least running tests against jdk8?

**Comment by kaidamasaki** [comment]
I've built and run tests against JDK8 locally, but I'll look into getting Jenkins doing that, too.

**Comment by velvia** [comment]
Nice!

**Comment by kaidamasaki** [comment]
Building on JDK8 now.

**Pull request merged**
